/**
 * Verifiable credibility signals (AIC-893 / REBUILD-HONEST Tier 3).
 *
 * Single source of truth for the "what we can actually stand behind" claims the
 * honest-proof surfaces render. This replaces the fabricated named testimonials
 * removed in AIC-890 with signals every one of which points to a real,
 * verifiable source RIGHT NOW — the hard guardrail from AIC-889 / FTC.
 *
 * HARD RULE (do not relax): every entry here must be true and sourced today.
 *   - BLS (OEWS salary tables + growth projections) is real: src/lib/market-data.ts
 *     fetches api.bls.gov and falls back to published BLS OEWS May-2023 tables.
 *   - "Built on Claude" is real: plans are generated by Anthropic's Claude.
 *   - "Secure checkout via Stripe" / "No account to start" are real product facts.
 *
 * DELIBERATELY OMITTED: O*NET and the LinkedIn Economic Graph. The AIC-893 brief
 * lists them as *candidate* Tier-3 sources, but the product does not currently
 * ingest either, so claiming them would be exactly the un-sourced claim the
 * guardrail forbids. Add them here ONLY once real ingestion exists.
 */

export interface CredibilitySignal {
  /** Short label rendered in the badge. */
  label: string;
  /** One-line substantiation shown as a tooltip / sub-label. */
  detail: string;
  /** lucide-react icon name used by CredibilityStrip. */
  icon: "database" | "sparkles" | "lock" | "user-check";
  /**
   * Which honest bucket this belongs to. `methodology` = how the plan is built,
   * `data` = external market sources, `security` = trust/handling.
   */
  kind: "methodology" | "data" | "security";
}

export const CREDIBILITY_SIGNALS: CredibilitySignal[] = [
  {
    label: "U.S. Bureau of Labor Statistics",
    detail:
      "Salary ranges and role-growth outlook use BLS OEWS data — public labor-market facts, not our users' results.",
    icon: "database",
    kind: "data",
  },
  {
    label: "Built on Claude",
    detail:
      "Your roadmap is generated by Anthropic's Claude, guided by a structured career-transition framework.",
    icon: "sparkles",
    kind: "methodology",
  },
  {
    label: "Secure checkout via Stripe",
    detail: "Payments are processed by Stripe. We never see or store your card details.",
    icon: "lock",
    kind: "security",
  },
  {
    label: "No account to start",
    detail: "Run a free snapshot with no signup and no credit card — you decide before you pay.",
    icon: "user-check",
    kind: "security",
  },
];

/**
 * Compact methodology line for inline contexts (onboarding plan, contextual
 * notes). Kept in sync with the signals above — every source named here is one
 * we genuinely use.
 */
export const METHODOLOGY_LINE =
  "Your plan is built by Claude from your own profile and grounded in U.S. Bureau of Labor Statistics labor-market data — real market facts, not invented outcomes.";
