import { notFound } from "next/navigation";
import { getSupabaseClient } from "@/lib/supabase";
import SiteNav from "@/components/SiteNav";
import type { PivotPlan, UserProfile, ValuesAssessment } from "@/lib/intake";
import ReportContent from "./ReportContent";
import CareerProfileCard from "@/components/CareerProfileCard";

interface Props {
  params: Promise<{ id: string }>;
}

export default async function ReportPage({ params }: Props) {
  const { id } = await params;
  const supabase = getSupabaseClient();

  const { data: report } = await supabase
    .from("reports")
    .select("*")
    .eq("id", id)
    .single();

  if (!report) notFound();

  const profile = report.profile as UserProfile;
  const plans = report.plans as PivotPlan[];
  const valuesAssessment = report.values_assessment as ValuesAssessment | null;

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white">
      <SiteNav />
      <main className="max-w-4xl mx-auto px-6 py-12">
        <div className="text-center mb-10">
          <p className="text-teal-400 font-semibold text-sm uppercase tracking-widest mb-3">
            Your Career Pivot Report
          </p>
          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-2">
            {profile.name ? `${profile.name}'s` : "Your"} Personalized Roadmap
          </h1>
          {profile.currentTitle && (
            <p className="text-slate-400 text-lg">
              {profile.currentTitle}
              {profile.currentIndustry ? ` · ${profile.currentIndustry}` : ""}
              {profile.yearsExperience ? ` · ${profile.yearsExperience} years experience` : ""}
            </p>
          )}
        </div>

        {valuesAssessment && (
          <CareerProfileCard assessment={valuesAssessment} />
        )}

        {profile.transferableSkills.length > 0 && (
          <div className="bg-slate-800/60 border border-slate-700 rounded-2xl p-6 mb-8">
            <h2 className="text-lg font-bold text-teal-400 mb-4">
              Transferable Skills Identified
              <span className="text-slate-500 text-sm font-normal ml-2">
                ({profile.transferableSkills.length})
              </span>
            </h2>
            <div className="flex flex-wrap gap-2">
              {profile.transferableSkills.map((skill) => (
                <span
                  key={skill}
                  className="px-3 py-1 bg-teal-900/40 border border-teal-700/50 rounded-full text-teal-300 text-sm"
                >
                  {skill}
                </span>
              ))}
            </div>
          </div>
        )}

        <ReportContent plans={plans} reportId={id} location={profile.location} />

        <div className="mt-12 text-center text-slate-500 text-xs">
          <p>Generated by AICareerPivot · {new Date(report.created_at).toLocaleDateString()}</p>
          <p className="mt-1">
            Questions? Reply to your receipt email or reach us at support@ai-career-pivot.com
          </p>
        </div>
      </main>
    </div>
  );
}
